version: '3.8'

x-mysql-setting: &mysql-setting
  MYSQL_USER: 'myproject-user'
  MYSQL_PASSWORD: 'P@ssw0rd'
  MYSQL_DATABASE: 'myproject'

services:
  app.tasks.myproject:
    build:
      context: ./src
    command: '--reload'
    environment:
      <<: *mysql-setting
      MYSQL_HOST: db.tasks.myproject
      MYSQL_PORT: 3306
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
    volumes:
      - "./src:/app"
  db.tasks.myproject:
    image: mysql:8
    environment:
      <<: *mysql-setting
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    ports:
      - '3306:3306'
    volumes:
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/data:/var/lib/mysql
  nginx.tasks.myproject:
    depends_on:
      - app.tasks.myproject
    build:
      context: ./docker/nginx
    environment:
      APP_HOST: app.tasks.myproject
    ports:
      - '8080:80'
    volumes:
      - ./src/collectstatic:/var/www/static
